version: 2.1
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - build_site
      - store_artifacts:
          path: docs/_build/html/
          destination: html

  push_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Add deployment key fingerprint for CircleCI to use for a push
      - add_ssh_keys:
          fingerprints:
            # The SSH key fingerprint
            - "c5:70:b9:1b:9a:cf:e3:88:25:9f:33:8e:ee:09:76:9f"

      - build_site

      - run:
          name: Pushing documentation to gh-pages
          command: |
            pip install --user ghp-import
            ghp-import --no-jekyll --push --message "Update documentation [skip ci]" docs/_build/html

workflows:
  version: 2
  default:
    jobs:
      - build_docs
      - push_docs:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - main

commands:
  build_site:
    description: "Build the site with sphinx"
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout
      # Python env
      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV

      - restore_cache:
          keys:
            - cache-pip
      - run: pip install --user -r docs/doc-requirements.txt
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd docs
            make html
